terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 32475064) >= this->size() (which is 222)
Read file tra_data/tra_data0.txt
read trajs: 4321, cost time:13.000000
Read file tra_data/tra_data1.txt
read trajs: 46003, cost time:100.000000
Read file tra_data/tra_data2.txt
read trajs: 84672, cost time:86.000000
Read file tra_data/tra_data3.txt
read trajs: 122200, cost time:87.000000
Read file tra_data/tra_data4.txt
read trajs: 173791, cost time:127.000000
Read file tra_data/tra_data5.txt
read trajs: 228321, cost time:132.000000
Read file tra_data/tra_data6.txt
read trajs: 289635, cost time:134.000000
Read file tra_data/tra_data7.txt
read trajs: 344567, cost time:130.000000
Read file tra_data/tra_data8.txt
read trajs: 399991, cost time:134.000000
Read file tra_data/tra_data9.txt
read trajs: 447244, cost time:106.000000
read trajs: 447244, cost time: -1049.000000
insert points: 42608713, grid: 5048,  cost time:-77.000000
